global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "fiap-prometheus-metrics-regions"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8080"]
  - job_name: "fiap-prometheus-metrics-contacts"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:7070"]
